import { vars } from "nativewind";

// Theme Schema
export const light = {
  // Colors
  primary: "rgba(19, 20, 74, 1)",
  secondary: "rgba(252, 96, 83, 1)",
  error: "rgba(165, 52, 40, 1)",
  background: "rgba(251, 251, 253, 1)",
  surface: "rgba(251, 251, 253, 1)",
  link: "rgba(46, 47, 138, 1)",
  button: "rgba(46, 47, 138, 1)",
  divider: "rgba(189, 189, 189, 1)",
  buttonGradient1: "rgba(19, 20, 74, 1)",
  buttonGradient2: "rgba(253, 96, 83, 1)",
  buttonGradient3: "rgba(249, 164, 46, 1)",
  buttonSecondaryGradient1: "rgba(50, 51, 103, 1)",
  buttonSecondaryGradient2: "rgba(118, 81, 118, 1)",
  buttonSecondaryGradient3: "rgba(138, 113, 136, 1)",
  bottomBarActive: "rgba(19, 20, 74, 1)",
  bottomBarShadow: "rgba(0, 0, 0, 0.07)",
  bottomBarSecondaryShadow: "rgba(224, 225, 239, 0.42)",
  textPrimary: "rgba(19, 20, 74, 1)",
  textSecondary: "rgb(70, 73, 78)",
  textPlaceholder: "rgba(93, 98, 104, 0.65)",
  cardBackground: "rgba(1, 1, 5, 0.68)",
  cardSecondaryBackground: "rgba(222, 220, 233, 0.67)",
  cardDisabledBackground: "rgba(189, 189, 189, 1)",
  shimmerBase: "rgba(205, 205, 205, 1)",
  circularProgress: "rgba(251, 251, 253, 1)",

  // Images
  bodyBackground: require("../assets/images/body_background_light.jpg"),
};

export const dark = {
  // Colors
  primary: "rgba(242, 242, 242, 1)",
  secondary: "rgba(19, 20, 74, 1)",
  error: "rgba(229, 115, 104, 1)",
  background: "rgba(33, 33, 33, 1)",
  surface: "rgba(33, 33, 33, 1)",
  link: "rgba(169, 169, 210, 1)",
  button: "rgba(169, 169, 210, 1)",
  divider: "rgba(66, 66, 66, 1)",
  buttonGradient1: "rgba(66, 67, 146, 1)",
  buttonGradient2: "rgba(138, 93, 137, 1)",
  buttonGradient3: "rgba(138, 113, 136, 1)",
  buttonSecondaryGradient1: "rgba(50, 50, 90, 1)",
  buttonSecondaryGradient2: "rgba(155, 72, 68, 1)",
  buttonSecondaryGradient3: "rgba(200, 121, 37, 1)",
  bottomBarActive: "rgba(230, 223, 223, 1)",
  bottomBarShadow: "rgba(255, 255, 255, 0.07)",
  bottomBarSecondaryShadow: "rgba(66, 67, 146, 0.54)",
  textPrimary: "rgba(230, 223, 223, 1)",
  textSecondary: "rgba(208, 207, 207, 1)",
  textPlaceholder: "rgba(208, 207, 207, 0.7)",
  cardBackground: "rgba(58, 57, 62, 1)",
  cardSecondaryBackground: "rgba(78, 75, 85, 0.91)",
  cardDisabledBackground: "rgba(66, 66, 66, 1)",
  shimmerBase: "rgba(103, 103, 103, 1)",
  circularProgress: "rgba(208, 156, 52, 1)",

  // Images
  bodyBackground: require("../assets/images/body_background_dark.jpg"),
};

// Apply colors inside vars() -> tailwind.config.js
export const themes = {
  light: vars({
    "--color-primary": light.primary,
    "--color-secondary": light.secondary,
    "--color-error": light.error,
    "--color-background": light.background,
    "--color-surface": light.surface,
    "--color-link": light.link,
    "--color-button": light.button,
    "--color-divider": light.divider,
    "--color-button-gradient-1": light.buttonGradient1,
    "--color-button-gradient-2": light.buttonGradient2,
    "--color-button-gradient-3": light.buttonGradient3,
    "--color-button-secondary-gradient-1": light.buttonSecondaryGradient1,
    "--color-button-secondary-gradient-2": light.buttonSecondaryGradient2,
    "--color-button-secondary-gradient-3": light.buttonSecondaryGradient3,
    "--color-bottom-bar-active": light.bottomBarActive,
    "--color-bottom-bar-shadow": light.bottomBarShadow,
    "--color-bottom-bar-secondary-shadow": light.bottomBarSecondaryShadow,
    "--color-text-primary": light.textPrimary,
    "--color-text-secondary": light.textSecondary,
    "--color-text-placeholder": light.textPlaceholder,
    "--color-card-background": light.cardBackground,
    "--color-card-secondary-background": light.cardSecondaryBackground,
    "--color-card-disabled-background": light.cardDisabledBackground,
    "--color-shimmer-base": light.shimmerBase,
    "--color-circular-progress": light.circularProgress,
  }),
  dark: vars({
    "--color-primary": dark.primary,
    "--color-secondary": dark.secondary,
    "--color-error": dark.error,
    "--color-background": dark.background,
    "--color-surface": dark.surface,
    "--color-link": dark.link,
    "--color-button": dark.button,
    "--color-divider": dark.divider,
    "--color-button-gradient-1": dark.buttonGradient1,
    "--color-button-gradient-2": dark.buttonGradient2,
    "--color-button-gradient-3": dark.buttonGradient3,
    "--color-button-secondary-gradient-1": dark.buttonSecondaryGradient1,
    "--color-button-secondary-gradient-2": dark.buttonSecondaryGradient2,
    "--color-button-secondary-gradient-3": dark.buttonSecondaryGradient3,
    "--color-bottom-bar-active": dark.bottomBarActive,
    "--color-bottom-bar-shadow": dark.bottomBarShadow,
    "--color-bottom-bar-secondary-shadow": dark.bottomBarSecondaryShadow,
    "--color-text-primary": dark.textPrimary,
    "--color-text-secondary": dark.textSecondary,
    "--color-text-placeholder": dark.textPlaceholder,
    "--color-card-background": dark.cardBackground,
    "--color-card-secondary-background": dark.cardSecondaryBackground,
    "--color-card-disabled-background": dark.cardDisabledBackground,
    "--color-shimmer-base": dark.shimmerBase,
    "--color-circular-progress": dark.circularProgress,
  }),
};
